version: "2"
services:
  plone:
    image: plone:5
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.schema.slate
    environment:
      ADDONS: "eea.schema.slate[test]"
      DEVELOP: "src/eea.schema.slate"
